services:
    db:
        image: postgres:16.2-alpine
        command: -p 5432
        expose:
            - 5432
        ports:
            - '5432:5432'
        volumes:
            - app-db-data:/var/lib/postgresql/
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - backend
    api:
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - backend
    redis:
        image: redis:7.4.1
        volumes:
        - redis:/var/lib/redis
        - redis-config:/usr/local/etc/redis/redis.conf
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        ports:
        - "6379:6379"
        networks:
            - backend
volumes:
    app-db-data:
    db-data:
    redis:
    redis-config:

networks:
    backend:
        driver: bridge
