services:
  postgres:
    image: postgres:18.1-bookworm
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '5433:5432'
    restart: always
  
  postgres-migrate:
    image: migrate/migrate:latest
    volumes:
      - ${PROJECT_ROOT}/internal/data/postgres/database/migration:/migration
  
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres-data:
  redis:
  redis-config: