services:
  db:
    image: postgres:latest
    command: -p 5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports: # only for local development
      - '5432:5432'

volumes:
  db-data: