services:
    bot:
        build: 
            context: bot
            dockerfile: Dockerfile
        env_file:
            - bot/.env
        # depends_on:
            # - api
            # - redis
        environment:
            - REDIS_URL=redis://redis:6379
            - API_URL=http://api:8000
        networks:
            - backend
    db:
        image: mongo:6-jammy
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
        env_file:
            - .env
        environment:
            - MONGODB_PASSWORD=password
            - MONGODB_USERNAME=mongodb
        networks:
            - backend
    api:
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - backend
    redis:
        image: redis:7.4.1
        volumes:
        - redis:/var/lib/redis
        - redis-config:/usr/local/etc/redis/redis.conf
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        ports:
        - "6379:6379"
        networks:
            - backend
volumes:
    db-data:
    redis:
    redis-config:

networks:
    backend:
        driver: bridge
