services:
    # bot:
    #     build: 
    #         context: bot
    #         dockerfile: Dockerfile
    #     env_file:
    #         - bot/.env
    #     # depends_on:
    #         # - api
    #         # - redis
    #     environment:
    #         - REDIS_URL=redis://redis:6379
    #         - API_URL=http://api:8000
    #     networks:
    #         - backend
    db:
        image: postgres:16.2-alpine
        command: -p 5432
        expose:
            - 5432
        ports:
            - '5432:5432'
        volumes:
            - app-db-data:/var/lib/postgresql/
        env_file:
            - ./api/.env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - backend
    api:
        build:
            ./api
        env_file:
            - ./api/.env
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - backend
    redis:
        image: redis:7.4.1
        volumes:
        - redis:/var/lib/redis
        - redis-config:/usr/local/etc/redis/redis.conf
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        ports:
        - "6379:6379"
        networks:
            - backend
volumes:
    app-db-data:
    db-data:
    redis:
    redis-config:

networks:
    backend:
        driver: bridge
