// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const agentExistsByUsername = `-- name: AgentExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM agents WHERE LOWER(username) = $1)
`

func (q *Queries) AgentExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, agentExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const changeAgentToken = `-- name: ChangeAgentToken :execrows
UPDATE agents
SET
    token_hash = $1
WHERE id = $2
`

type ChangeAgentTokenParams struct {
	TokenHash string
	ID        uuid.UUID
}

func (q *Queries) ChangeAgentToken(ctx context.Context, arg ChangeAgentTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeAgentToken, arg.TokenHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAgentsByUser = `-- name: CountAgentsByUser :one
SELECT COUNT(*) FROM agents WHERE user_id = $1
`

func (q *Queries) CountAgentsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (user_id, username, token_hash) VALUES ($1, $2, $3)
RETURNING id, user_id, username, token_hash, created_at
`

type CreateAgentParams struct {
	UserID    uuid.UUID
	Username  string
	TokenHash string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.UserID, arg.Username, arg.TokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, user_id, username, token_hash, created_at
FROM agents
WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByToken = `-- name: GetAgentByToken :one
SELECT id, user_id, username, token_hash, created_at
FROM agents
WHERE token_hash = $1
`

func (q *Queries) GetAgentByToken(ctx context.Context, tokenHash string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByToken, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentsByUser = `-- name: GetAgentsByUser :many
SELECT id, user_id, username, token_hash, created_at
FROM agents
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetAgentsByUser(ctx context.Context, userID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, getAgentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TokenHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
