// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (max_item_slots, max_resource_volume)
VALUES ($1, $2)
RETURNING id, max_item_slots, max_resource_volume
`

type CreateInventoryParams struct {
	MaxItemSlots      int32
	MaxResourceVolume int32
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.MaxItemSlots, arg.MaxResourceVolume)
	var i Inventory
	err := row.Scan(&i.ID, &i.MaxItemSlots, &i.MaxResourceVolume)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (inventory_id, item_type, metadata)
VALUES ($1, $2, $3)
RETURNING id, inventory_id, item_type, metadata, created_at
`

type CreateInventoryItemParams struct {
	InventoryID uuid.UUID
	ItemType    string
	Metadata    []byte
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem, arg.InventoryID, arg.ItemType, arg.Metadata)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.ItemType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryResource = `-- name: CreateInventoryResource :one
INSERT INTO inventory_resources (inventory_id, resource_type, amount)
VALUES ($1, $2, $3)
RETURNING inventory_id, resource_type, amount
`

type CreateInventoryResourceParams struct {
	InventoryID  uuid.UUID
	ResourceType string
	Amount       int64
}

func (q *Queries) CreateInventoryResource(ctx context.Context, arg CreateInventoryResourceParams) (InventoryResource, error) {
	row := q.db.QueryRow(ctx, createInventoryResource, arg.InventoryID, arg.ResourceType, arg.Amount)
	var i InventoryResource
	err := row.Scan(&i.InventoryID, &i.ResourceType, &i.Amount)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :execrows
DELETE FROM inventory_items WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInventoryItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInventoryResource = `-- name: DeleteInventoryResource :execrows
DELETE FROM inventory_resources WHERE inventory_id = $1 AND resource_type = $2
`

type DeleteInventoryResourceParams struct {
	InventoryID  uuid.UUID
	ResourceType string
}

func (q *Queries) DeleteInventoryResource(ctx context.Context, arg DeleteInventoryResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInventoryResource, arg.InventoryID, arg.ResourceType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInventoryByID = `-- name: GetInventoryByID :one
SELECT id, max_item_slots, max_resource_volume FROM inventories
WHERE id = $1
`

func (q *Queries) GetInventoryByID(ctx context.Context, id uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByID, id)
	var i Inventory
	err := row.Scan(&i.ID, &i.MaxItemSlots, &i.MaxResourceVolume)
	return i, err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, inventory_id, item_type, metadata, created_at FROM inventory_items
WHERE id = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, id uuid.UUID) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.ItemType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryItems = `-- name: GetInventoryItems :many
SELECT id, inventory_id, item_type, metadata, created_at FROM inventory_items
WHERE inventory_id = $1
ORDER BY created_at
`

func (q *Queries) GetInventoryItems(ctx context.Context, inventoryID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, getInventoryItems, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.InventoryID,
			&i.ItemType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryOwner = `-- name: GetInventoryOwner :one
SELECT
    id AS owner_id,
    'AGENT' AS owner_type
FROM agents
WHERE agents.inventory_id = $1

UNION ALL

SELECT
    id AS owner_id,
    'SHIP' AS owner_type
FROM ships
WHERE ships.inventory_id = $1
`

type GetInventoryOwnerRow struct {
	OwnerID   uuid.UUID
	OwnerType string
}

func (q *Queries) GetInventoryOwner(ctx context.Context, inventoryID uuid.UUID) (GetInventoryOwnerRow, error) {
	row := q.db.QueryRow(ctx, getInventoryOwner, inventoryID)
	var i GetInventoryOwnerRow
	err := row.Scan(&i.OwnerID, &i.OwnerType)
	return i, err
}

const getInventoryResource = `-- name: GetInventoryResource :one
SELECT inventory_id, resource_type, amount FROM inventory_resources
WHERE inventory_id = $1 AND resource_type = $2
`

type GetInventoryResourceParams struct {
	InventoryID  uuid.UUID
	ResourceType string
}

func (q *Queries) GetInventoryResource(ctx context.Context, arg GetInventoryResourceParams) (InventoryResource, error) {
	row := q.db.QueryRow(ctx, getInventoryResource, arg.InventoryID, arg.ResourceType)
	var i InventoryResource
	err := row.Scan(&i.InventoryID, &i.ResourceType, &i.Amount)
	return i, err
}

const getInventoryResources = `-- name: GetInventoryResources :many

SELECT inventory_id, resource_type, amount FROM inventory_resources
WHERE inventory_id = $1
ORDER BY amount
`

// -- name: AddInventoryResource :one
// INSERT INTO inventory_resources (inventory_id, resource_type, amount)
// VALUES ($1, $2, $3)
// ON CONFLICT (inventory_id, resource_type)
// DO UPDATE SET
//
//	amount = amount + $3
//
// RETURNING *;
func (q *Queries) GetInventoryResources(ctx context.Context, inventoryID uuid.UUID) ([]InventoryResource, error) {
	rows, err := q.db.Query(ctx, getInventoryResources, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryResource
	for rows.Next() {
		var i InventoryResource
		if err := rows.Scan(&i.InventoryID, &i.ResourceType, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one
UPDATE inventories
SET
    max_item_slots = $2,
    max_resource_volume = $3
WHERE id = $1
RETURNING id, max_item_slots, max_resource_volume
`

type UpdateInventoryParams struct {
	ID                uuid.UUID
	MaxItemSlots      int32
	MaxResourceVolume int32
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventory, arg.ID, arg.MaxItemSlots, arg.MaxResourceVolume)
	var i Inventory
	err := row.Scan(&i.ID, &i.MaxItemSlots, &i.MaxResourceVolume)
	return i, err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items
SET
    inventory_id = $2,
    metadata = $3
WHERE id = $1
RETURNING id, inventory_id, item_type, metadata, created_at
`

type UpdateInventoryItemParams struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	Metadata    []byte
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem, arg.ID, arg.InventoryID, arg.Metadata)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.ItemType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateInventoryResource = `-- name: UpdateInventoryResource :one
UPDATE inventory_resources
SET
    inventory_id = $1,
    amount = $3
WHERE inventory_id = $1 AND resource_type = $2
RETURNING inventory_id, resource_type, amount
`

type UpdateInventoryResourceParams struct {
	InventoryID  uuid.UUID
	ResourceType string
	Amount       int64
}

func (q *Queries) UpdateInventoryResource(ctx context.Context, arg UpdateInventoryResourceParams) (InventoryResource, error) {
	row := q.db.QueryRow(ctx, updateInventoryResource, arg.InventoryID, arg.ResourceType, arg.Amount)
	var i InventoryResource
	err := row.Scan(&i.InventoryID, &i.ResourceType, &i.Amount)
	return i, err
}
