// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShipStatus string

const (
	ShipStatusORBIT  ShipStatus = "ORBIT"
	ShipStatusDOCKED ShipStatus = "DOCKED"
)

func (e *ShipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShipStatus(s)
	case string:
		*e = ShipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShipStatus: %T", src)
	}
	return nil
}

type NullShipStatus struct {
	ShipStatus ShipStatus
	Valid      bool // Valid is true if ShipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShipStatus), nil
}

type ShipType string

const (
	ShipTypeTRADER ShipType = "TRADER"
	ShipTypeSCOUT  ShipType = "SCOUT"
	ShipTypeMINER  ShipType = "MINER"
)

func (e *ShipType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShipType(s)
	case string:
		*e = ShipType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShipType: %T", src)
	}
	return nil
}

type NullShipType struct {
	ShipType ShipType
	Valid    bool // Valid is true if ShipType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShipType) Scan(value interface{}) error {
	if value == nil {
		ns.ShipType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShipType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShipType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShipType), nil
}

type Agent struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Username    string
	TokenHash   string
	CreatedAt   pgtype.Timestamp
	InventoryID uuid.UUID
}

type Inventory struct {
	ID                uuid.UUID
	MaxItemSlots      int32
	MaxResourceVolume int32
}

type InventoryItem struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	ItemType    string
	Metadata    []byte
	CreatedAt   pgtype.Timestamp
}

type InventoryResource struct {
	InventoryID  uuid.UUID
	ResourceType string
	Amount       int64
}

type Ship struct {
	ID          uuid.UUID
	AgentID     uuid.UUID
	Type        ShipType
	Active      bool
	SystemX     int32
	SystemY     int32
	Status      ShipStatus
	CreatedAt   pgtype.Timestamp
	Name        string
	InventoryID uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
}
