// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_deposits.sql

package database

import (
	"context"
)

const getResourceDeposit = `-- name: GetResourceDeposit :one
SELECT system_x, system_y, loc_type, loc_id, resource_type, remaining, last_mined_at FROM resource_deposit_states
WHERE system_x = $1 AND system_y = $2 AND loc_type = $3 AND loc_id = $4 AND resource_type = $5
`

type GetResourceDepositParams struct {
	SystemX      int32
	SystemY      int32
	LocType      LocationType
	LocID        int32
	ResourceType string
}

func (q *Queries) GetResourceDeposit(ctx context.Context, arg GetResourceDepositParams) (ResourceDepositState, error) {
	row := q.db.QueryRow(ctx, getResourceDeposit,
		arg.SystemX,
		arg.SystemY,
		arg.LocType,
		arg.LocID,
		arg.ResourceType,
	)
	var i ResourceDepositState
	err := row.Scan(
		&i.SystemX,
		&i.SystemY,
		&i.LocType,
		&i.LocID,
		&i.ResourceType,
		&i.Remaining,
		&i.LastMinedAt,
	)
	return i, err
}

const getResourceDepositForUpdate = `-- name: GetResourceDepositForUpdate :one
SELECT system_x, system_y, loc_type, loc_id, resource_type, remaining, last_mined_at FROM resource_deposit_states
WHERE system_x = $1 AND system_y = $2 AND loc_type = $3 AND loc_id = $4 AND resource_type = $5
FOR UPDATE
`

type GetResourceDepositForUpdateParams struct {
	SystemX      int32
	SystemY      int32
	LocType      LocationType
	LocID        int32
	ResourceType string
}

func (q *Queries) GetResourceDepositForUpdate(ctx context.Context, arg GetResourceDepositForUpdateParams) (ResourceDepositState, error) {
	row := q.db.QueryRow(ctx, getResourceDepositForUpdate,
		arg.SystemX,
		arg.SystemY,
		arg.LocType,
		arg.LocID,
		arg.ResourceType,
	)
	var i ResourceDepositState
	err := row.Scan(
		&i.SystemX,
		&i.SystemY,
		&i.LocType,
		&i.LocID,
		&i.ResourceType,
		&i.Remaining,
		&i.LastMinedAt,
	)
	return i, err
}

const getSystemResourceDeposits = `-- name: GetSystemResourceDeposits :many
SELECT system_x, system_y, loc_type, loc_id, resource_type, remaining, last_mined_at FROM resource_deposit_states
WHERE system_x = $1 AND system_y = $2
`

type GetSystemResourceDepositsParams struct {
	SystemX int32
	SystemY int32
}

func (q *Queries) GetSystemResourceDeposits(ctx context.Context, arg GetSystemResourceDepositsParams) ([]ResourceDepositState, error) {
	rows, err := q.db.Query(ctx, getSystemResourceDeposits, arg.SystemX, arg.SystemY)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceDepositState
	for rows.Next() {
		var i ResourceDepositState
		if err := rows.Scan(
			&i.SystemX,
			&i.SystemY,
			&i.LocType,
			&i.LocID,
			&i.ResourceType,
			&i.Remaining,
			&i.LastMinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResourceDeposit = `-- name: UpsertResourceDeposit :exec
INSERT INTO resource_deposit_states (system_x, system_y, loc_type, loc_id, resource_type, remaining, last_mined_at) 
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (system_x, system_y, loc_type, loc_id, resource_type)
DO UPDATE SET
    remaining = EXCLUDED.remaining,
    last_mined_at = EXCLUDED.last_mined_at
`

type UpsertResourceDepositParams struct {
	SystemX      int32
	SystemY      int32
	LocType      LocationType
	LocID        int32
	ResourceType string
	Remaining    int64
}

func (q *Queries) UpsertResourceDeposit(ctx context.Context, arg UpsertResourceDepositParams) error {
	_, err := q.db.Exec(ctx, upsertResourceDeposit,
		arg.SystemX,
		arg.SystemY,
		arg.LocType,
		arg.LocID,
		arg.ResourceType,
		arg.Remaining,
	)
	return err
}
