// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ships.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createShip = `-- name: CreateShip :one
INSERT INTO ships (agent_id, type, active, system_x, system_y, status, name) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, type, active, system_x, system_y, status, created_at, name
`

type CreateShipParams struct {
	AgentID uuid.UUID
	Type    ShipType
	Active  bool
	SystemX int32
	SystemY int32
	Status  ShipStatus
	Name    string
}

func (q *Queries) CreateShip(ctx context.Context, arg CreateShipParams) (Ship, error) {
	row := q.db.QueryRow(ctx, createShip,
		arg.AgentID,
		arg.Type,
		arg.Active,
		arg.SystemX,
		arg.SystemY,
		arg.Status,
		arg.Name,
	)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Active,
		&i.SystemX,
		&i.SystemY,
		&i.Status,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getActiveShipByAgent = `-- name: GetActiveShipByAgent :one
SELECT id, agent_id, type, active, system_x, system_y, status, created_at, name
FROM ships
WHERE agent_id = $1 AND active = true
`

func (q *Queries) GetActiveShipByAgent(ctx context.Context, agentID uuid.UUID) (Ship, error) {
	row := q.db.QueryRow(ctx, getActiveShipByAgent, agentID)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Active,
		&i.SystemX,
		&i.SystemY,
		&i.Status,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getShipByID = `-- name: GetShipByID :one
SELECT id, agent_id, type, active, system_x, system_y, status, created_at, name
FROM ships
WHERE id = $1
`

func (q *Queries) GetShipByID(ctx context.Context, id uuid.UUID) (Ship, error) {
	row := q.db.QueryRow(ctx, getShipByID, id)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Active,
		&i.SystemX,
		&i.SystemY,
		&i.Status,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getShipsByAgent = `-- name: GetShipsByAgent :many
SELECT id, agent_id, type, active, system_x, system_y, status, created_at, name
FROM ships
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetShipsByAgent(ctx context.Context, agentID uuid.UUID) ([]Ship, error) {
	rows, err := q.db.Query(ctx, getShipsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ship
	for rows.Next() {
		var i Ship
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Type,
			&i.Active,
			&i.SystemX,
			&i.SystemY,
			&i.Status,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveShip = `-- name: SaveShip :one
UPDATE ships
SET
    type = $2,
    active = $3,
    system_x = $4,
    system_y = $5,
    status = $6,
    name = $7
WHERE id = $1
RETURNING id, agent_id, type, active, system_x, system_y, status, created_at, name
`

type SaveShipParams struct {
	ID      uuid.UUID
	Type    ShipType
	Active  bool
	SystemX int32
	SystemY int32
	Status  ShipStatus
	Name    string
}

func (q *Queries) SaveShip(ctx context.Context, arg SaveShipParams) (Ship, error) {
	row := q.db.QueryRow(ctx, saveShip,
		arg.ID,
		arg.Type,
		arg.Active,
		arg.SystemX,
		arg.SystemY,
		arg.Status,
		arg.Name,
	)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Active,
		&i.SystemX,
		&i.SystemY,
		&i.Status,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}
