// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ship_modules.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createShipModule = `-- name: CreateShipModule :one
INSERT INTO ship_modules (ship_id, module_type)
VALUES ($1, $2)
RETURNING ship_id, module_type
`

type CreateShipModuleParams struct {
	ShipID     uuid.UUID
	ModuleType string
}

func (q *Queries) CreateShipModule(ctx context.Context, arg CreateShipModuleParams) (ShipModule, error) {
	row := q.db.QueryRow(ctx, createShipModule, arg.ShipID, arg.ModuleType)
	var i ShipModule
	err := row.Scan(&i.ShipID, &i.ModuleType)
	return i, err
}

const deleteShipModule = `-- name: DeleteShipModule :exec
DELETE FROM ship_modules
WHERE ship_id = $1 AND module_type = $2
`

type DeleteShipModuleParams struct {
	ShipID     uuid.UUID
	ModuleType string
}

func (q *Queries) DeleteShipModule(ctx context.Context, arg DeleteShipModuleParams) error {
	_, err := q.db.Exec(ctx, deleteShipModule, arg.ShipID, arg.ModuleType)
	return err
}

const getShipModule = `-- name: GetShipModule :one
SELECT ship_id, module_type FROM ship_modules
WHERE ship_id = $1 AND module_type = $2
`

type GetShipModuleParams struct {
	ShipID     uuid.UUID
	ModuleType string
}

func (q *Queries) GetShipModule(ctx context.Context, arg GetShipModuleParams) (ShipModule, error) {
	row := q.db.QueryRow(ctx, getShipModule, arg.ShipID, arg.ModuleType)
	var i ShipModule
	err := row.Scan(&i.ShipID, &i.ModuleType)
	return i, err
}

const getShipModules = `-- name: GetShipModules :many
SELECT ship_id, module_type FROM ship_modules
WHERE ship_id = $1
`

func (q *Queries) GetShipModules(ctx context.Context, shipID uuid.UUID) ([]ShipModule, error) {
	rows, err := q.db.Query(ctx, getShipModules, shipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipModule
	for rows.Next() {
		var i ShipModule
		if err := rows.Scan(&i.ShipID, &i.ModuleType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
