"""spaceship_and_character_fields

Revision ID: 133dc6d6eed6
Revises: 56067e65b1e1
Create Date: 2025-08-16 11:40:57.102060

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "133dc6d6eed6"
down_revision: Union[str, Sequence[str], None] = "56067e65b1e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column("in_spaceship", sa.Boolean(), nullable=True, default=False),
    )
    op.add_column("spaceships", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spaceships", "active")
    op.drop_column("characters", "in_spaceship")
    # ### end Alembic commands ###
