"""points

Revision ID: 22c6765cdcf6
Revises: 2cd6ed7dbf75
Create Date: 2026-03-15 15:37:23.995543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c6765cdcf6'
down_revision: Union[str, Sequence[str], None] = '2cd6ed7dbf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('point_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('characters', sa.Column('point_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('characters_planet_id_fkey'), 'characters', type_='foreignkey')
    op.drop_constraint(op.f('characters_system_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'points', ['point_id'], ['id'])
    op.drop_column('characters', 'planet_id')
    op.drop_column('characters', 'system_id')
    op.drop_column('characters', 'location')
    op.add_column('planets', sa.Column('point_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('planets_system_id_fkey'), 'planets', type_='foreignkey')
    op.create_foreign_key(None, 'planets', 'points', ['point_id'], ['id'])
    op.drop_column('planets', 'system_id')
    op.add_column('spaceships', sa.Column('point_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('spaceships_planet_id_fkey'), 'spaceships', type_='foreignkey')
    op.drop_constraint(op.f('spaceships_system_id_fkey'), 'spaceships', type_='foreignkey')
    op.create_foreign_key(None, 'spaceships', 'points', ['point_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('spaceships', 'planet_id')
    op.drop_column('spaceships', 'system_id')
    op.drop_column('spaceships', 'location')
    op.drop_column('systems', 'locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('locations', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('spaceships', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('spaceships', sa.Column('system_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('spaceships', sa.Column('planet_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'spaceships', type_='foreignkey')
    op.create_foreign_key(op.f('spaceships_system_id_fkey'), 'spaceships', 'systems', ['system_id'], ['id'])
    op.create_foreign_key(op.f('spaceships_planet_id_fkey'), 'spaceships', 'planets', ['planet_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('spaceships', 'point_id')
    op.add_column('planets', sa.Column('system_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'planets', type_='foreignkey')
    op.create_foreign_key(op.f('planets_system_id_fkey'), 'planets', 'systems', ['system_id'], ['id'])
    op.drop_column('planets', 'point_id')
    op.add_column('characters', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('system_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('planet_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_system_id_fkey'), 'characters', 'systems', ['system_id'], ['id'])
    op.create_foreign_key(op.f('characters_planet_id_fkey'), 'characters', 'planets', ['planet_id'], ['id'])
    op.drop_column('characters', 'point_id')
    op.drop_table('stations')
    op.drop_table('points')
    # ### end Alembic commands ###
