"""item_durability

Revision ID: 2cd6ed7dbf75
Revises: 5ffca751c8b3
Create Date: 2025-08-19 14:33:43.162765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd6ed7dbf75'
down_revision: Union[str, Sequence[str], None] = '5ffca751c8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('durability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'durability')
    # ### end Alembic commands ###
