"""system_connections

Revision ID: 2d7138e118dc
Revises: 620f3cf5e27c
Create Date: 2025-08-17 17:30:56.390529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7138e118dc'
down_revision: Union[str, Sequence[str], None] = '620f3cf5e27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_from_id', sa.String(), nullable=False),
    sa.Column('system_to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['system_from_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['system_to_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_connections')
    # ### end Alembic commands ###
