"""inventories

Revision ID: 5ffca751c8b3
Revises: 2d7138e118dc
Create Date: 2025-08-17 20:40:47.044944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5ffca751c8b3"
down_revision: Union[str, Sequence[str], None] = "2d7138e118dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner",
            sa.Enum("CHARACTER", "SPACESHIP", name="inventoryownerenum"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("inventory_id", sa.Uuid(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("inventory_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources")
    op.drop_table("items")
    op.drop_table("inventories")
    # ### end Alembic commands ###
