"""character_planet_relation

Revision ID: 620f3cf5e27c
Revises: 662092349152
Create Date: 2025-08-17 14:04:33.269359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "620f3cf5e27c"
down_revision: Union[str, Sequence[str], None] = "662092349152"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("planet_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "characters", "planets", ["planet_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_column("characters", "planet_id")
    # ### end Alembic commands ###
