"""character_system_relation

Revision ID: 662092349152
Revises: 133dc6d6eed6
Create Date: 2025-08-16 21:41:58.483937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "662092349152"
down_revision: Union[str, Sequence[str], None] = "133dc6d6eed6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("system_id", sa.String(), nullable=False))
    op.alter_column(
        "characters", "in_spaceship", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.create_foreign_key(None, "characters", "systems", ["system_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.alter_column(
        "characters", "in_spaceship", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_column("characters", "system_id")
    # ### end Alembic commands ###
