[package]
name = "dsbot"
version = "0.3.1"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
lib-core.workspace = true
lib-utils.workspace = true
poise = "0.6.1"
serenity = "0.12.2"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3.18"
