openapi: 3.0.3
info:
  title: AstraGalaxy API
  version: 0.1.0
  description: API for space exploration game
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/v1/auth/login:
    $ref: "paths/users/login.yaml"
  /api/v1/auth/register:
    $ref: "paths/users/register.yaml"
  /api/v1/auth/me:
    $ref: "paths/users/me.yaml"
  /api/v1/agents:
    $ref: "paths/agents/agents.yaml"
  /api/v1/agents/my:
    $ref: "paths/agents/my.yaml"
  /api/v1/agents/current:
    $ref: "paths/agents/current.yaml"
  /api/v1/agents/{id}/reset-token:
    $ref: "paths/agents/reset-token.yaml"
  /api/v1/ships/my:
    $ref: "paths/ships/my.yaml"
  /api/v1/ships/my/active:
    $ref: "paths/ships/my-active.yaml"
  /api/v1/ships/my/{id}/rename:
    $ref: "paths/ships/my-rename.yaml"
  /api/v1/ships/my/active/radar:
    $ref: "paths/ships/my-radar.yaml"
  /api/v1/ships/my/{id}/active:
    $ref: "paths/ships/my-activate.yaml"
  /api/v1/inventories/my:
    $ref: "paths/inventories/my.yaml"
  /api/v1/inventories/my/ships/{id}:
    $ref: "paths/inventories/my-ships.yaml"
  /api/v1/inventories/transfer-resources:
    $ref: "paths/inventories/transfer-resources.yaml"
  /api/v1/inventories/transfer-items:
    $ref: "paths/inventories/transfer-items.yaml"
components:
  securitySchemes:
    UserAuth:
      type: http
      name: User JWT auth
      bearerFormat: JWT
      scheme: Bearer
      in: header
    AgentAuth:
      type: http
      name: Agent auth
      scheme: Bearer
      in: header
