name: Lint

on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          args: --timeout=5m ./cmd/web/...
