name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download libraries
        run: sudo apt update && apt install -y \
          libssl-dev \
          libsodium23 \
          libsecp256k1-dev \
          zlib1g

      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
